-- Table , 시퀀스 등 구조 정의
DROP SEQUENCE SQ_SIMPLE_APPROVAL;
CREATE SEQUENCE SQ_SIMPLE_APPROVAL START WITH 1 INCREMENT BY 1;

DROP TABLE TB_SIMPLE_APPROVAL CASCADE CONSTRAINT;

-- 결재 정보 테이블
CREATE TABLE TB_SIMPLE_APPROVAL
(
    SANO            NUMBER NOT NULL PRIMARY KEY,       -- 결재번호(PK), 시퀀스
    APPROVAL_DATE   VARCHAR2(1000) ,                   -- 결재일자 : YYYY-MM-DD HH24:MI:SS
    APPROVAL_AMOUNT NUMBER NOT NULL
);